version: "3.8"
services:
  openlibrary-proxy:
    build: .
    container_name: openlibrary-proxy
    ports:
      - "${PORT:-8080}:${PORT:-8080}"
    environment:
      # ---- Tweak these in Unraid's Docker template ----
      PORT: "${PORT:-8080}"               # Host/container port
      OL_PAGE_SIZE: "${OL_PAGE_SIZE:-200}"# Max works per author request (1-500)
      LOG_LEVEL: "${LOG_LEVEL:-info}"     # debug|info|warn|error
      ENABLE_CACHE: "${ENABLE_CACHE:-true}"     # true|false - in-memory cache
      CACHE_TTL_MS: "${CACHE_TTL_MS:-600000}"   # default 10 minutes
      CACHE_MAX: "${CACHE_MAX:-500}"            # max cached entries
      CORS_ORIGIN: "${CORS_ORIGIN:-*}"          # allow web UI/testing if needed
      BASE_PATH: "${BASE_PATH:-}"               # optional: serve under a subpath (e.g., /books)
    restart: unless-stopped
